### ISSUE TITLE
Update integration tests for QuickStarts to use Quarkus dist

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak-quickstarts#287]
### Description

Integration tests and GitHub actions, as well as steps within quickstarts needs to be updated to use the Quarkus distribution.

**Comment by pedroigor** [comment]
Please, re-introduce tests for https://github.com/keycloak/keycloak-quickstarts/pull/302.

**Comment by mposolda** [comment]
Closing as this was already done and quickstarts in the `main` branch are using Quarkus distribution now
