### ISSUE TITLE
Update user-storage-jpa example to use Quarkus

### ISSUE THREAD

**Issue by domitopp** [keycloak/keycloak-quickstarts#299]
### Description

The [https://github.com/keycloak/keycloak-quickstarts/tree/latest/user-storage-jpa](user-storage-jpa example) is still based on Wildfly.
How to migrate to Quarkus?

### Motivation

We have a custom user storage provider based on the example user-storage-jpa.
We have to migrate to Keycloak based on Quarkus until June 2022.
It would be very helpful if you could update the example to work with the Quarkus distribution.

**Comment by serhii900** [comment]
> I have the same issue. When I use the user-storage-jpa as is, without any updates. Create the jar file by `mvn clean package` then copy it to the `<keycloak_path>/providers` directory, then `<keycloak_path>/bin/kc build`, then `<keycloak_path>/bin/kc start-dev` i have received the error:
> 
> ```
> ERROR: Unexpected error when starting the server in (development) mode
> ERROR: Failed to start quarkus
> ERROR: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
> ERROR: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
> For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
> ```

I have the same problem

**Comment by niki17nl** [comment]
> У меня такая же проблема. Когда я использую user-storage-jpa как есть, без каких-либо обновлений. Создайте файл jar, `mvn clean package`затем скопируйте его в `<keycloak_path>/providers`каталог, `<keycloak_path>/bin/kc build`затем `<keycloak_path>/bin/kc start-dev`я получил сообщение об ошибке:
> 
> ```
> ERROR: Unexpected error when starting the server in (development) mode
> ERROR: Failed to start quarkus
> ERROR: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
> ERROR: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
> For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
> ```



> I have the same issue. When I use the user-storage-jpa as is, without any updates. Create the jar file by `mvn clean package` then copy it to the `<keycloak_path>/providers` directory, then `<keycloak_path>/bin/kc build`, then `<keycloak_path>/bin/kc start-dev` i have received the error:
> 
> ```
> ERROR: Unexpected error when starting the server in (development) mode
> ERROR: Failed to start quarkus
> ERROR: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
> ERROR: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
> For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
> ```

I have the same problem...

**Comment by pedroigor** [comment]
We should be looking at that ASAP. We need to review the support for multiple PUs and data sources.

**Comment by nostra83** [comment]
Same problem here as well.

> > У меня такая же проблема. Когда я использую user-storage-jpa как есть, без каких-либо обновлений. Создайте файл jar, `mvn clean package`затем скопируйте его в `<keycloak_path>/providers`каталог, `<keycloak_path>/bin/kc build`затем `<keycloak_path>/bin/kc start-dev`я получил сообщение об ошибке:
> > ```
> > ERROR: Unexpected error when starting the server in (development) mode
> > ERROR: Failed to start quarkus
> > ERROR: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
> > ERROR: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
> > For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
> > ```
> 
> > I have the same issue. When I use the user-storage-jpa as is, without any updates. Create the jar file by `mvn clean package` then copy it to the `<keycloak_path>/providers` directory, then `<keycloak_path>/bin/kc build`, then `<keycloak_path>/bin/kc start-dev` i have received the error:
> > ```
> > ERROR: Unexpected error when starting the server in (development) mode
> > ERROR: Failed to start quarkus
> > ERROR: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
> > ERROR: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
> > For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
> > ```
> 
> I have the same problem...
Same problem here as well

**Comment by ahus1** [comment]
There is now a a more recent issue #303 that also contains a linked PR. Therefore I close this issue as a duplicate.
