### ISSUE TITLE
Latest openshift-examples/keycloak.yaml of 17.0.0 does not work

### ISSUE THREAD

**Issue by xingxingxia** [keycloak/keycloak-quickstarts#300]
### Describe the bug

In the past, using below command from https://www.keycloak.org/getting-started/getting-started-openshift :
```
$ oc process -f https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/latest/openshift-examples/keycloak.yaml \
    -p KEYCLOAK_USER=admin \
    -p KEYCLOAK_PASSWORD=admin \
    -p NAMESPACE=keycloak \
| oc create -f -
service/keycloak created
route.route.openshift.io/keycloak created
deploymentconfig.apps.openshift.io/keycloak created
```
The keycloak pod can be Running. But now, it is CrashLoopBackOff:
```
$ oc get po
NAME                READY   STATUS             RESTARTS      AGE
keycloak-1-6pmv9    0/1     CrashLoopBackOff   5 (24s ago)   3m27s
keycloak-1-deploy   1/1     Running            0             3m31s
$ oc describe po keycloak-1-6pmv9
...
Events:
...
  Normal   Pulled     2m41s (x4 over 3m33s)  kubelet            Container image "quay.io/keycloak/keycloak:17.0.0" already present on machine
...
  Warning  BackOff    2m8s (x13 over 3m31s)  kubelet            Back-off restarting failed container
$ oc logs keycloak-1-6pmv9
Keycloak - Open Source Identity and Access Management

Find more information at: https://www.keycloak.org/docs/latest

Usage:

kc.sh [OPTIONS] [COMMAND]
...
  Please, take a look at the documentation for more details before deploying in
production.

Use "kc.sh start --help" for the available options when starting the server.
Use "kc.sh <command> --help" for more information about other commands.
```
Looks like quay.io/keycloak/keycloak:17.0.0 does not set additional necessary arguments for kc.sh to start up. It only sets:
```
      Entrypoint:
      - /opt/keycloak/bin/kc.sh
      Env:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - container=oci
```
Either quay.io/keycloak/keycloak:17.0.0 should be updated with full args for start-up, or openshift-examples/keycloak.yaml needs be updated with those full args.

### Version

17.0.0

### Expected behavior

See above, pod should be Running

### Actual behavior

See above, pod is CrashLoopBackOff

### How to Reproduce?

See above

### Anything else?
None

**Comment by xingxingxia** [comment]
@stianst , could you help fix, or help find who is the corresponding guy to fix? Thanks. CC @pierreprinetti .

**Comment by DGuhr** [comment]
Hey @xingxingxia sorry for the late response. I did a change [here](https://github.com/keycloak/keycloak-quickstarts/pull/296/files), but it seems it went down to nirvana after switching from latest to main. will provide it again :)

**Comment by DGuhr** [comment]
PR is sent again in #304 - also a PR to overhaul the guide itself is at https://github.com/keycloak/keycloak-web/pull/288

**Comment by xingxingxia** [comment]
@DGuhr thanks, but I now add comments there, hope be adopted.
