### ISSUE TITLE
Getting No page found when accessing http://localhost:8080/auth/

### ISSUE THREAD

**Issue by prakashayappan** [keycloak/keycloak-quickstarts#305]
### Describe the bug

In Windows, just installed KeyCloak 17

Tried to open http://localhost:8080/auth/, getting Page Not Found

### Version

17.0.0

**Comment by DGuhr** [comment]
Hi, @prakashayappan  

For issues like this one, please use the [main repository](https://github.com/keycloak/keycloak), specifically the [Discussions / Q/A ](https://github.com/keycloak/keycloak/discussions/categories/q-a) section or the [Issues](https://github.com/keycloak/keycloak/issues) section. When you think you've found a bug and file a bug ticket there, please include more information than "does not work", for example the exact error message you get, log output, and your configuration (pls don't include sensitive information such as passwords.)

The quickstarts repository is specifically meant to provide code examples to get you an idea of the capabilities of extending Keycloak. 

Thank you.

Best regards,
Dominik
