### ISSUE TITLE
Re-evaluate empty volume mount in OpenShift Quickstart

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak-quickstarts#307]
### Description

We currently [need to use](https://github.com/keycloak/keycloak-quickstarts/blob/a6922780eac9acbfc7fcdb73a325838b548922de/openshift-examples/keycloak.yaml#L90-L96) empty volume mounts to work around the OpenShift security constrains that prevent pods from creating files related to the H2. We should reconsider this and ideally remove this workaround.

**Comment by vmuzikar** [comment]
@andreaTP With https://github.com/keycloak/keycloak/pull/10783 merged, I think we can remove the volume mounts. WDYT?

**Comment by andreaTP** [comment]
I would like to add that mounting an external folder where the application will write data is overall good practice (e.g. ppl might want to mount a PVC etc.); so, no harm ...
