### ISSUE TITLE
Upgrade to the existing "UserStorageJpa" example for the new Keycloak Quarkus version

### ISSUE THREAD

**Issue by iacolucci** [keycloak/keycloak-quickstarts#314]
### Description

The "UserStorageJpa" example is based on the old keycloak Wildfly versione using JEE tecnology and maybe I think it will have to be upgraded, indicating hot to create an additional datasource for external legacy DB and so on.

### Motivation

It should be added beacause people should know hot to integrate an existing users legacy database where keycloak can read users data.

**Comment by DGuhr** [comment]
Hi. The quickstart was adjusted to the quarkus version here: https://github.com/keycloak/keycloak-quickstarts/tree/main/user-storage-jpa - didn't make it to latest branch (accidentally), but it works for 18 and I hope you are unblocked by following the quickstart :) Closing here for now.
