### ISSUE TITLE
Please modify the contents of the 'app-authz-spring-security/README.md'

### ISSUE THREAD

**Issue by ZhangqyTJ** [keycloak/keycloak-quickstarts#370]
### Describe the bug

Following the execution steps in the app-authz-spring-security/README.md  will not run successfully
Wrong position

![微信图片_20230110164005](https://user-images.githubusercontent.com/95729803/211502299-b03e1145-ff0f-4ba9-9e90-141714965c43.png)

Correct command:
      ./kc.sh -Djboss.socket.binding.port-offset=100
      mvn -f ../authz-js-policies clean install && cp ../authz-js-policies/target/authz-js-policies.jar {KEYCLOAK_HOME}/providers

### Version

22.0.2

**Comment by pedroigor** [comment]
Closing as outdated. Please look the quickstart available at https://github.com/keycloak/keycloak-quickstarts/tree/latest/spring/rest-authz-resource-server.
