### ISSUE TITLE
Add quickstarts for spring boot 3 and spring security 6

### ISSUE THREAD

**Issue by mirzaprangon** [keycloak/keycloak-quickstarts#374]
### Description

Currently all the quickstarts in the repository for spring is using spring boot 2.

Keycloak have depcreated the adapter for spring. Also alot have changed in the spring boot 3 and spring security 6.
I suggest to add quickstart projects in the repository using spring boot 3 and spring security 6. Quickstart projects will help a lot for beginners, like me to understand and get up and running with Keycloak.

**Comment by kkcmadhu** [comment]
Will basic auth be supported ? the spring-boot-2-keycloak library which is now deprecated supports basic auth and bearer..

**Comment by pedroigor** [comment]
Closing as outdated. The examples about using Spring and Spring Security are available at https://github.com/keycloak/keycloak-quickstarts/tree/latest/spring.

The adapter is now deprecated. See https://www.keycloak.org/docs/latest/securing_apps/#_spring_security_adapter.
