### ISSUE TITLE
app-profile-jee-vanilla needs to be updated to OIDC

### ISSUE THREAD

**Issue by Toma5OD** [keycloak/keycloak-quickstarts#383]
### Description

app-profile-jee-vanilla needs to be updated to use OIDC and to stop the need for the legacy adapters. Changes required to readme etc

### Motivation

Due to changes to Keycloak and move from using Javax package to Jakarta and switch from using basic security to using OIDC the legacy adapters are now no longer required and the javax packages need to be switched and security configuration updated.

**Comment by pedroigor** [comment]
Closing as outdated. See https://github.com/keycloak/keycloak-quickstarts/pull/388#issuecomment-1554586329.
