### ISSUE TITLE
Not possible to compile quickstarts with jdk 17

### ISSUE THREAD

**Issue by martin-kanis** [keycloak/keycloak-quickstarts#398]
### Describe the bug

Execution default-war of goal org.apache.maven.plugins:maven-war-plugin:2.6:war failed: Unable to load the mojo 'war' in the plugin 'org.apache.maven.plugins:maven-war-plugin:2.6' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: null

### Version

999.0.0-Snapshot

### How to Reproduce?

mvn clean install -DskipTests with jdk 17

**Comment by mposolda** [comment]
I am resolving as there was refactoring of quickstarts recently and quickstarts are using Java 17 and should work fine.
