### ISSUE TITLE
Add MySQL to the User Federation menu

### ISSUE THREAD

**Issue by marcellopato** [keycloak/keycloak-quickstarts#423]
### Description

I am trying to add a new User Federation for MySQL, or any JDBC connection manually, but it is not working at all.
I think you could create this to be default, hun?
Or there is already a good way to do it and I couldn't find yet?

### Motivation

This is not the first time I see this kind of demand: Use an existing database to log users to a new app. So I think this could be a wonderful enhancement!

### Details

Well, I think the `mysql-connector***.jar` file could be avaiable out of the box when you install Keycloak, as you already have drivers for LDAP and Kerberos providers

**Comment by pedroigor** [comment]
Thanks for the report. Closing as outdated. The repository has changed and the issue no longer is valid.

Please, look at the [database guide](https://www.keycloak.org/server/db) about how to configure different databases. Keycloak now provides built-in support for different database and their drivers (except Oracle).
