### ISSUE TITLE
Issue when trying to deploy app-authz-jee-vanilla show module not fund

### ISSUE THREAD

**Issue by yiheng321** [keycloak/keycloak-quickstarts#449]
### Describe the bug

As following the guide, in my windows PC,

It give me **error** when run "mvn clean package wildfly:deploy"

**Dignostic:** Tested with "mvn clean package" and get successful 
suspect issue is related to wildfly: deploy.

[ERROR] Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.2.2.Final:deploy (default-cli) on project keycloak-app-authz-jee-vanilla: Failed to execute goal deploy: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" => {"jboss.module.service.\"deployment.app-authz-jee-vanilla.war\".main" => "WFLYSRV0179: Failed to load module: deployment.app-authz-jee-vanilla.war
[ERROR]     Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-authz-client"}}}}
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.2.2.Final:deploy (default-cli) on project keycloak-app-authz-jee-vanilla: Failed to execute goal deploy: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" => {"jboss.module.service.\"deployment.app-authz-jee-vanilla.war\".main" => "WFLYSRV0179: Failed to load module: deployment.app-authz-jee-vanilla.war
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-authz-client"}}}}

### Version

        <groupId>org.keycloak.quickstarts</groupId>         <artifactId>keycloak-quickstart-parent</artifactId>         <version>7.4.0.GA</version>

**Comment by pedroigor** [comment]
Thanks for the report. Closing as outdated. The repository has changed and the issue no longer is valid.
