### ISSUE TITLE
Jakart QS deployment step doesn't work - multiple issues

### ISSUE THREAD

**Issue by lhanusov** [keycloak/keycloak-quickstarts#469]
### Describe the bug

Information on how to import quickstart-realm into container is not straightforward, please update link: 
* https://www.keycloak.org/docs/latest/server_admin/index.html#proc-creating-a-realm_server_administration_guide

Fix the non working links: https://github.com/keycloak/keycloak-quickstarts/tree/latest/jakarta/jaxrs-resource-server#access-the-quickstart
* replace service
* for jakarta-jaxrs-resource-server

OIDC projects don't mention that OIDC adapter is already part of Wildfly as the Elytron OIDC Adapter.

Wrong version of JAVA (must be JDK 17):
* https://github.com/keycloak/keycloak-quickstarts/tree/latest/jakarta/servlet-saml-service-provider#system-requirements

Missing information that adapter installation is needed (download page: https://www.keycloak.org/downloads): 
* SAML: https://github.com/keycloak/keycloak-quickstarts/tree/latest/jakarta/servlet-saml-service-provider#starting-the-wildfly-server

Outdated plugin version doesn't work with JDK 17 (mvn-wildfly-plugin): https://github.com/keycloak/keycloak-quickstarts/blob/latest/pom.xml#L60
* https://mvnrepository.com/artifact/org.wildfly.plugins/wildfly-maven-plugin/4.1.1.Final

### Version

latest

### Expected behavior

Command: mvn -Djakarta clean wildfly:deploy should deploy war to Wildfly and connect OIDC client to Keycloak.

### Actual behavior

Doesn't work and fails on multiple failures.

**Comment by pedroigor** [comment]
Closing as outdated. See https://github.com/keycloak/keycloak-quickstarts/pull/470#issuecomment-1720244866.
