### ISSUE TITLE
$$VERSION$$ in example yaml possibly not resolved

### ISSUE THREAD

**Issue by andreas-ibm** [keycloak/keycloak-quickstarts#473]
### Describe the bug

I'm no k8s expert, let's start with that!

I have a script that effectively follows https://www.keycloak.org/getting-started/getting-started-kube, so at one stage it runs:
```bash
kubectl create -f https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/latest/kubernetes/keycloak.yaml
```

which used to work fine, but since #458 and #459 it doesn't...

If I manually download the yaml and replace `$$VERSION$$` with the latest version it works again, so I'm *pretty* sure it's the cause.

Is there meant to be some magic that I'm missing? I can obviously put some sed magic in my script to do the replacement, but I'd suggest the above getting-started page would need improving to tell users they need to perform the substitution.

### Version

22.0.1

### Expected behavior

Keycloak up and running

### Actual behavior

Got this error:
```
Events:
  Type     Reason         Age                   From               Message
  ----     ------         ----                  ----               -------
  Normal   Scheduled      17m                   default-scheduler  Successfully assigned default/keycloak-794869df8-trspp to worker-3
  Warning  Failed         15m (x12 over 17m)    kubelet            Error: InvalidImageName
  Warning  InspectFailed  2m51s (x72 over 17m)  kubelet            Failed to apply default image tag "quay.io/keycloak/keycloak:$$VERSION$$": couldn't parse image reference "quay.io/keycloak/keycloak:$$VERSION$$": invalid reference format
```

### How to Reproduce?

Follow instruction on https://www.keycloak.org/getting-started/getting-started-kube

**Comment by vmuzikar** [comment]
@andreas-ibm Thanks for the report. This indeed seems like a bug.

**Comment by goseind** [comment]
I have just encountered the same problem. Would it make sense to use a specific tag again in this manifest, or update the documentation to let users know that they need to change the version tag before applying?

**Comment by stianst** [comment]
Fixed the script + updated the latest branch to now point to 22.0.3

**Comment by andreas-ibm** [comment]
Cool, confirmed fixed

**Comment by virtualdxs** [comment]
The script seems to be broken again, as I just hit this issue trying to deploy Keycloak based on the getting started guide.

**Comment by vmuzikar** [comment]
@virtualdxs Should be fixed in https://github.com/keycloak/keycloak-quickstarts/pull/504.
