### ISSUE TITLE
QuickStart for Java?

### ISSUE THREAD

**Issue by Mike4Online** [keycloak/keycloak-quickstarts#480]
### Description

The Securing Apps document says the [Keycloak Java Adapters are deprecated](https://www.keycloak.org/docs/latest/securing_apps/#keycloak-java-adapters), and directs readers to this Quickstart repository.  One of those Java Adapters is [the InstalledAdapter](https://www.keycloak.org/docs/latest/securing_apps/#_installed_adapter) for integrating Java Swing, JavaFX and Java CLI applications with Keycloak.  But I do not see any example in the Quickstarts repository for integrating such Java applications with Keycloak 22 or newer (other than the Jakarta examples, which I are for Java applications that use a Jakarta servlet container, or for integrating WildFly via REST).

I have a custom application written in Java (with Swing for its UI, and no servlet container of any kind, nor any use of WildFly).  It currently uses `keycloak-installed-adapter` and OpenID Connect to integrate with a Keycloak server:

1. Should I be switching from `keycloak-installed-adapter` to something from the Quickstarts repository?  If so, can you clarify which examples demonstrate integrating a Java Desktop (JavaFX or Swing) / CLI application with Keycloak?  Of if such examples are missing, can you please add them?
2. Can I keep using `keycloak-installed-adapter`, or is it deprecated?
3. Does `keycloak-installed-adapter` version 22 require my application to run on Java 17?

Thanks.

### Motivation

A Quickstart for Java Desktop / CLI applications would ensure a smooth upgrade path for developers who have relied on the now-deprecated InstalledAdapter.

**Comment by pedroigor** [comment]
> 1. Should I be switching from keycloak-installed-adapter to something from the Quickstarts repository? If so, can you clarify which examples demonstrate integrating a Java Desktop (JavaFX or Swing) / CLI application with Keycloak? Of if such examples are missing, can you please add them?

Hi @Mike4Online. We never had an example for `KeycloakInstalled`, unfortunately. I also don't know about any alternative.

Very unlikely we are going to provide a quickstart for it.

> 2. Can I keep using keycloak-installed-adapter, or is it deprecated?

There is no date yet when we are going to stop publishing it. You can still use it.

Once they are removed, I would say that any previous version should still be functional as (AFAIK) they are based on the standard OpenID Connect.

> 3. Does keycloak-installed-adapter version 22 require my application to run on Java 17?

Yes. The artifacts are built using JDK 17.

**Comment by Mike4Online** [comment]
@pedroigor,

Thanks for your responses.  It sounds like my two use cases will be supported for some time to come:

1. Connecting to a Keycloak 21 or newer server using a Java rich-text client that uses an older version of Keycloak InstalledAdapter, e.g. Keycloak 17 InstalledAdapter.
2. Updating my Java rich-text client to use the latest version (22) of Keycloak InstalledAdapter, for connecting to a Keycloak server running Keycloak 22.

Going beyond Keycloak 22 is a little unclear at this time, since older InstalledAdapter versions may support the newer Keycloak server versions.  Or maybe they won't.

Before closing this issue, I think it would help clarify things if the details of your response were reflected in the [Securing Apps document](https://www.keycloak.org/docs/latest/securing_apps/#keycloak-java-adapters), under the topic **2.3. Keycloak Java adapters**.  See Docs: securing_apps/topics/oidc/java/java-adapters.adoc

**Comment by pedroigor** [comment]
> Before closing this issue, I think it would help clarify things if the details of your response were reflected in the [Securing Apps document](https://www.keycloak.org/docs/latest/securing_apps/#keycloak-java-adapters), under the topic 2.3. Keycloak Java adapters. See Docs: securing_apps/topics/oidc/java/java-adapters.adoc

I'm not sure if we can add this to the official documentation. Although Keycloak is a certified OpenID Connect implementation, creating expectations in the community about their compatibility with newer versions is a strong commitment, and not aligned with the adapter roadmap.

This is especially true for any adapter that supports Keycloak-specific capabilities. I usually like to use logout as an example as well as registering nodes at the server.

But in regards to `KeycloakInstalled`, it relies on pure OpenID Connect (nice and simple). More likely it will work with newer releases. I wouldn't be surprised if we see an alternative there over time (based on it, perhaps), looks like a handy tool for desktop developers.

**Comment by Mike4Online** [comment]
Thank you.
