### ISSUE TITLE
extension/user-storage-simple does not build

### ISSUE THREAD

**Issue by minusdavid** [keycloak/keycloak-quickstarts#499]
### Describe the bug

`[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/keycloak/quickstarts/keycloak-quickstart-parent/22.0.4/keycloak-quickstart-parent-22.0.4.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.keycloak.quickstarts:keycloak-user-storage-properties:22.0.4: Could not find artifact org.keycloak.quickstarts:keycloak-quickstart-parent:pom:22.0.4 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 20, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.keycloak.quickstarts:keycloak-user-storage-properties:22.0.4 (/usr/src/app/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.keycloak.quickstarts:keycloak-user-storage-properties:22.0.4: Could not find artifact org.keycloak.quickstarts:keycloak-quickstart-parent:pom:22.0.4 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 20, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException`

### Version

21.0.2

**Comment by minusdavid** [comment]
When I go to https://repo.maven.apache.org/maven2/org/keycloak/ I don't see any reference to quickstarts.

I've previously used https://github.com/dasniko/keycloak-user-spi-demo but I was hoping that there'd be a different more up-to-date example...

**Comment by minusdavid** [comment]
I was also hoping this would build so I could work through it using https://www.keycloak.org/docs/latest/server_development/#_user-storage-spi

**Comment by martin-kanis** [comment]
Currently it works for me with ` mvn clean install -Dextension`
