### ISSUE TITLE
Where is the old authenticator example?

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak-quickstarts#553]
### Describe the bug

According to this, the example should be under extensions:
https://github.com/keycloak/keycloak/commit/1f772d29575e67ca86b30697a2d4088c1cdbd260

I recall seeing it there, but I can't find it anymore. Is it deprecated now? 

### Version

24.0.3

**Comment by mposolda** [comment]
@oculos Update: The PR to quickstarts was here https://github.com/keycloak/keycloak-quickstarts/pull/540 , however it was sent to `keycloak:latest` and hence it was automatically removed during the release of Keycloak 24.0.3 as correct branch for pull requests is `keycloak:main` .

**Comment by cornelpurcel** [comment]
Hi @mposolda , can I try to take care of the PR to introduce the Authenticator example back?
