### ISSUE TITLE
Workflow failure - Jakarta - SAMLServiceProviderTest.testAccessAccountManagement

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak-quickstarts#609]
### Describe the bug

```
Error:  Failures: 
Error:    SAMLServiceProviderTest.testAccessAccountManagement:146 Should display account management page
Error:    SAMLServiceProviderTest.testLogin:121
[INFO] 
Error:  Tests run: 2, Failures: 2, Errors: 0, Skipped: 0
```

https://github.com/keycloak/keycloak-quickstarts/actions/runs/11137594725/job/30951266367

### Version

latest

### Anything else?

Re-run of the action helped. So looks like a flakiness.

There is related flakiness https://github.com/keycloak/keycloak-quickstarts/issues/618

**Comment by mposolda** [comment]
Re-run of the action helped. So looks like a flakiness. Will take a look.

**Comment by miquelsi** [comment]
Failed again: https://github.com/keycloak/keycloak-quickstarts/actions/runs/11397206768/job/31712286651

**Comment by miquelsi** [comment]
Failed again: https://github.com/keycloak/keycloak-quickstarts/actions/runs/11511624855/job/32045344396
