### ISSUE TITLE
Workflow failure - Node.js

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak-quickstarts#610]
### Describe the bug

https://github.com/keycloak/keycloak-quickstarts/actions/runs/11267196975/job/31331917651

### Version

latest

### Anything else?

It passed in latest nightly build from 2024-10-14 - https://github.com/keycloak/keycloak-quickstarts/actions/runs/11320766480 . So might be just a flakiness. Before fixing it, see [here](https://github.com/keycloak/keycloak-quickstarts/actions) if still applicable and how often it is failing.

**Comment by jonkoops** [comment]
Looks like this workflow hasn't failed in more than [a couple of months](https://github.com/keycloak/keycloak-quickstarts/actions?page=4&query=event%3Aschedule). I think we can safely close this.
